package com.kotlinspring.dto

import jakarta.validation.constraints.NotBlank

data class CourseDTO( // A data container to hold Course Data
    val id: Int?, // to be generated by the DB, is nullable to be created by DB
    @get:NotBlank(message = "courseDTO.name must not be blank")
    var name: String,
    @get:NotBlank(message = "courseDTO.category must not be blank")
    var category: String
)