package com.kotlinspring.dto

data class CourseDTO( // A data container to hold Course Data
    val id: Int?, // to be generated by the DB, is nullable to be created by DB
    var name: String,
    var category: String
)